import { NexaraSignalLoom } from '@/components/nexara-signal-loom';
import { NexaraCoreCard } from '@/components/nexara-core-card';

const plugins = ['BetterCooking','BetterSurvival','BlissSMPS3','CheatSentinel','CoinsSim','DonutSMPCore','Equinox','HoloPoint','InventoryInsurance','ItemEdit','NOROMC','PortFolio','RankForge','RealisticEssentials','RegionSentry','Sentinel','SimplePlots','SkinRestorer','SunsetAC','SunsetDungeons','SunsetPlayers','SunsetRanks','SunsetUI','TowerDefense','VNMinions','YEETCANNON'];
const products = [
  { label:'web', title:'Nexara', text:'A full AI workspace for chat, games, and creation.' },
  { label:'mobile', title:'NexaraAPK', text:'Taking the product with me beyond the browser.' },
  { label:'desktop', title:'NexaraWindows', text:'A focused Windows shell for a faster daily workflow.' },
  { label:'devtools', title:'NexaraIDE', text:'An IDE experience built around the way I actually work.' },
  { label:'terminal', title:'NexaraCLI', text:'The command-line layer for builders who prefer speed.' },
];

export default function Home() {
  return <main>
    <nav className="nav-shell"><a className="brand" href="#top"><span className="brand-mark">K</span><span>K1NGMR<span className="brand-dot">.</span></span></a><div className="nav-links"><a href="#work">Work</a><a href="#plugins">Plugins</a><a href="#story">About</a></div><a className="nav-cta" href="#contact">Let&apos;s connect <span>↗</span></a></nav>
    <section id="top" className="hero section-pad"><div className="hero-copy"><div className="eyebrow"><span className="status-dot" /> building from Portugal · open to ambitious teams</div><p className="identity-line">Ananda Thapa <span>·</span> K1NGMR</p><h1>I make big ideas<br /><em>feel inevitable.</em></h1><p className="hero-lede">I&apos;m Ananda, a product-minded builder working across AI, developer tools, game systems, and the spaces in between.</p><div className="hero-actions"><a className="button button-dark" href="#work">See what I&apos;m building <span>↓</span></a><a className="text-link" href="https://github.com/K1NGMR" target="_blank" rel="noreferrer">GitHub <span>↗</span></a></div></div><div className="hero-orbit"><NexaraSignalLoom /></div></section>
    <section className="signal-strip"><div><strong>30+</strong><span>plugins shipped</span></div><div><strong>5</strong><span>Nexara surfaces</span></div><div><strong>∞</strong><span>curiosity left</span></div><div className="strip-note">A builder&apos;s portfolio, in motion <span>→</span></div></section>
    <section id="work" className="section-pad work-section"><div className="section-intro"><p className="kicker">01 / selected work</p><h2>Different surfaces.<br /><span>Same obsession.</span></h2><p>I like making complex things feel clear, fast, and a little more alive, whether it&apos;s a game mechanic, a security layer, or a whole product ecosystem.</p></div><div className="feature-card"><div className="feature-top"><span className="card-label">01: flagship system</span><span className="live-tag"><i /> in progress</span></div><div className="feature-grid"><div><div className="nexara-word">nexara<span>°</span></div><h3>A personal AI ecosystem<br />with room to grow.</h3><p>One idea, expanded across web, mobile, Windows, an IDE, and the terminal. Nexara is my long-running experiment in making powerful tools feel personal.</p><a className="card-link" href="#nexara">Explore the system <span>↗</span></a></div><NexaraCoreCard /></div></div></section>
    <section id="nexara" className="section-pad system-section"><div className="system-heading"><p className="kicker">The Nexara stack</p><h2>One vision.<br /><em>Many ways in.</em></h2></div><div className="product-list">{products.map((product,index)=><div className="product-row" key={product.title}><span className="product-index">0{index+1}</span><span className="product-label">{product.label}</span><h3>{product.title}</h3><p>{product.text}</p><span className="row-arrow">↗</span></div>)}</div></section>
    <section id="plugins" className="section-pad plugins-section"><div className="plugins-heading"><div><p className="kicker">02 / systems &amp; craft</p><h2>Small plugins.<br /><span>Real worlds.</span></h2></div><p>My plugin work started in Minecraft and became a crash course in designing reliable systems: economy, moderation, progression, security, and everything that makes a community feel like home.</p></div><div className="plugin-cloud">{plugins.map((plugin,index)=><span className={index%5===0?'plugin-chip chip-accent':'plugin-chip'} key={plugin}><i />{plugin}</span>)}</div><div className="plugin-foot"><span>26 projects surfaced from my Plugins workspace</span><a href="#contact">Ask me about the architecture <span>↗</span></a></div></section>
    <section id="story" className="story-section"><div className="story-inner section-pad"><div className="story-stamp">KM<br /><span>2026</span></div><div><p className="kicker light">03 / a little context</p><h2>I don&apos;t wait for<br /><em>permission to build.</em></h2><p className="story-copy">I learn by making. I move between product thinking and the details that make a product work, shipping experiments, rebuilding the pieces that bug me, and turning rough ideas into things people can actually use.</p><p className="story-copy">Right now, that means growing Nexara, exploring better AI tooling, and keeping a healthy lab of smaller projects alive.</p></div></div></section>
    <section id="contact" className="contact-section section-pad"><p className="kicker">04 / next chapter</p><h2>Let&apos;s make something<br /><em>worth remembering.</em></h2><p>Collaborations, or just a good conversation about what&apos;s next.</p><div className="contact-meta"><span>Discord</span><strong>liquade0610</strong></div><div className="contact-actions"><a className="button button-coral" href="https://github.com/K1NGMR" target="_blank" rel="noreferrer">Find me on GitHub <span>↗</span></a><a className="text-link" href="#top">Back to top ↑</a></div></section>
    <footer><span>© 2026 Ananda Thapa</span><span>Also known as K1NGMR · built with curiosity.</span><span>Portugal <span className="footer-dot">●</span></span></footer>
  </main>;
}
